<template>
<div>
    <h2>档案</h2>
    <scroll class="content" >
      <ul>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
        <li>ala</li>
      </ul>
    </scroll>
</div>


</template>

<script>
import Scroll from 'components/common/scroll/Scroll'
export default {
  name: 'Profile',
  components:{
    Scroll
  }
}
</script>

<style scoped>
.content{
  height:300px;
  background-color:red;
  overflow: hidden;
}
</style>